name: Church Commit and PR API CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build project
          run: mvn clean install

    sonar:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build, Testes e JaCoCo
          run: mvn clean verify --batch-mode --update-snapshots

        - name: Upload cobertura JaCoCo para SonarQube
          run: |
            mvn sonar:sonar \
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
                -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            
    
